######################################################################
# Automatically generated by qmake (3.0) Thu Jul 27 21:10:21 2017
######################################################################

TEMPLATE = app
TARGET = qosmcache
INCLUDEPATH += .

QT += widgets positioning websockets webview quick

RESOURCES += qosmcache.qml ../index_allinone.html

# Input
HEADERS += poswindow.h
#FORMS += poswindow.ui
SOURCES += poswindow.cpp qtmain.cpp
